### ISSUE TITLE
CNAME warning

### ISSUE THREAD

**Issue by angelofallars** [algodrip/algodrip-site#1]
When I modified the [README.md](https://github.com/algodrip/algodrip-site/blob/main/README.md), I was sent an email with this warning:

![warning](https://i.imgur.com/rFl4GOE.png)

There is a [CNAME](https://github.com/algodrip/algodrip-site/blob/main/CNAME) file in the repo, but it seems like it hasn't been set up properly yet.

**Comment by nafumie** [comment]
Issue fixed on dns side. Thanks for reporting!
